; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitc-02]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c3-devkitc-02
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DTARGET_MAC_ADDRESS='""'
    -DWIFI_SSID='""'
    -DWIFI_PASSWORD='""'
    -DBOOT_PIN_BUTTON=9
    -DDEVICE_NAME='"WOL-ESP32C3"'
    -DMQTT_ACCESS_TOKEN='""'
    -DMQTT_BROKER_ADDRESS='""'
    -DMQTT_BROKER_PORT=1883

lib_deps =
    a7md0/WakeOnLan @ 1.1.7
    https://github.com/arduino-libraries/ArduinoHttpClient.git
    https://github.com/thingsboard/pubsubclient.git
    https://github.com/thingsboard/thingsboard-client-sdk.git
    https://github.com/RobTillaart/DHT20.git